title: ChatGPT vs. Content Design
description: This is my final project for Vistula.
theme: just-the-docs

url: https://Lipkowski.github.io/Possibilities_and_limitations_of_ChatGPT_in_terms_of_content_design

aux_links:
  GitHub Repository: https://github.com/Lipkowski/just-the-docs
  
color_scheme: nil

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Created by Przemysław Lipkowski, 2023
lipkowski1996@gmail.com"
