title: Possibilities and limitations of ChatGPT in terms of content design
description: This is my final project for Vistula.
theme: just-the-docs

url: https://Lipkowski.github.io/Possibilities_and_limitations_of_ChatGPT_in_terms_of_content_design

aux_links:
  Template Repository: https://github.com/Lipkowski/just-the-docs
  
color_scheme: dark

heading_anchors: true
